name: Publish
on:
  push:
    tags:
      - "*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Create a new builder instance
        run: docker buildx create --name mybuilder --use

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build, tag, and push the builder image to Github ghcr
        id: build-builder-image
        env:
          REGISTRY: ${{ env.REGISTRY }}
          REPOSITORY: ${{ env.IMAGE_NAME }}
          IMAGE_TAG_LATEST: latest
          IMAGE_TAG_COMMIT: ${{ github.ref_name }}
        run: |
          #!/bin/bash

          # Function to check if the tag is a prerelease
          hasPrerelease() {
            [[ "$1" == *"-"* ]]
          }

          LATEST=""

          # Check if the tag is a prerelease
          if ! hasPrerelease "$IMAGE_TAG_COMMIT"; then
            LATEST="-t $REGISTRY/$REPOSITORY:$IMAGE_TAG_LATEST"
          fi

          # Get the current tag and create the Dockerfile
          cat <<EOF > Dockerfile
          FROM node:20-alpine

          # The port that your application listens to.
          EXPOSE 8000

          WORKDIR /app

          # Install Deno
          RUN apk add --no-cache curl unzip
          RUN curl -fsSL https://deno.land/install.sh | sh
          RUN mv /root/.deno/bin/deno /usr/local/bin/deno

          # Verify installations
          RUN node --version && npm --version && npx --version && deno --version

          # Cache deno dependencies
          RUN DENO_DIR=/daemon-deno-dir deno cache jsr:@deco/deco@$IMAGE_TAG_COMMIT/scripts/run

          # Create deno user and set up directories
          RUN addgroup -g 1000 deno && adduser -u 1000 -G deno -s /bin/sh -D deno
          RUN mkdir -p /home/deno && chown -R deno:deno /home/deno && mkdir /app/deco && chown -R deno:deno /app && mkdir -p /deno-dir && chown -R deno:deno /deno-dir && chown -R deno:deno /daemon-deno-dir

          # Prefer not to run as root.
          USER deno

          WORKDIR /app/deco
          EOF

          # Build and push the Docker image
          docker buildx build --platform linux/amd64,linux/arm64 $LATEST -t $REGISTRY/$REPOSITORY:$IMAGE_TAG_COMMIT --push .

          # Set the GitHub Actions outputs
          if [ -n "$LATEST" ]; then
            echo "::set-output name=image_builder_latest::$REGISTRY/$REPOSITORY:$IMAGE_TAG_LATEST"
          fi
          echo "::set-output name=image_builder_commit::$REGISTRY/$REPOSITORY:$IMAGE_TAG_COMMIT"