name: Publish
on:
  push:
    tags:
      - "*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Create a new builder instance
        run: docker buildx create --name mybuilder --use

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build, tag, and push the builder image to Github ghcr
        id: build-builder-image
        env:
          REGISTRY: ${{ env.REGISTRY }}
          REPOSITORY: ${{ env.IMAGE_NAME }}
          IMAGE_TAG_LATEST: latest
          IMAGE_TAG_COMMIT: ${{ github.ref_name }}
        run: |
          #!/bin/bash

          # Function to check if the tag is a prerelease
          hasPrerelease() {
            [[ "$1" == *"-"* ]]
          }

          LATEST=""

          # Check if the tag is a prerelease
          if ! hasPrerelease "$IMAGE_TAG_COMMIT"; then
            LATEST="-t $REGISTRY/$REPOSITORY:$IMAGE_TAG_LATEST"
          fi

          # Get the current tag and create the Dockerfile
          cat <<EOF > Dockerfile
          FROM denoland/deno:alpine-2.4.0

          # The port that your application listens to.
          EXPOSE 8000

          WORKDIR /app

          # Install dependencies and Node.js
          RUN apk update && apk add --no-cache nodejs npm

          # Verify npm is available and install wrangler CLI globally
          RUN npm --version && npm install -g wrangler

          # Set up directories and permissions
          RUN mkdir -p /home/deno && chown -R deno:deno /home/deno && mkdir /app/deco && chown -R deno:deno /app && mkdir -p /deno-dir && chown -R deno:deno /deno-dir && chown -R deno:deno /daemon-deno-dir

          # Prefer not to run as root.
          USER deno

          WORKDIR /app/deco
          EOF

          # Build and push the Docker image
          docker buildx build --platform linux/amd64,linux/arm64 $LATEST -t $REGISTRY/$REPOSITORY:$IMAGE_TAG_COMMIT --push .

          # Set the GitHub Actions outputs
          if [ -n "$LATEST" ]; then
            echo "::set-output name=image_builder_latest::$REGISTRY/$REPOSITORY:$IMAGE_TAG_LATEST"
          fi
          echo "::set-output name=image_builder_commit::$REGISTRY/$REPOSITORY:$IMAGE_TAG_COMMIT"